name: Device support request
description: Request support for a new device
title: Add support for <DEVICE>
labels: ["device"]
body:
  - type: markdown
    attributes:
      value: "Thank you for your interest in OpenAndroidInstaller!"
  - type: markdown
    attributes:
      value: "To get your device supported, please take the time to fill out this form."
  - type: markdown
    attributes:
      value: "|"
  - type: checkboxes
    attributes:
      label: Is your device already requested?
      description: Please search to see if an issue for your device already exists.
      options:
      - label: I have searched the existing issues
        required: true
  - type: markdown
    attributes:
      value: "---"
  - type: markdown
    attributes:
      value: "**Please input your device's details below:**"
  - type: input
    attributes:
      label: Brand
      description: The brand / manufacturer of your device
      placeholder: Google
    validations:
      required: true
  - type: input
    attributes:
      label: Name
      description: The name of your device
      placeholder: Pixel 7
    validations:
      required: true
  - type: input
    attributes:
      label: Device code
      description: The device code OAI gave you in the error message
      placeholder: panther
    validations:
      required: true
  - type: input
    attributes:
      label: Model
      description: The model name of your device (only required, if there are several models)
      placeholder: GVU6C
    validations:
      required: false
